import {
  commandModifier,
  openTargetTitles,
  optionModifier,
  saveAsTargetTitles,
  saveTargetTitles,
  settingsTargetTitles,
  shiftModifier,
  type NativeMenuConfig,
} from "@legend-apps/native-menu";

export const diffMenuConfig: NativeMenuConfig[] = [
  {
    id: "app",
    title: "Application",
    systemMenu: "app",
    items: [
      {
        id: "settings",
        targetTitles: settingsTargetTitles,
        enabled: true,
      },
      {
        id: "checkForUpdates",
        title: "Check for Updates...",
        enabled: true,
        placement: { after: "About Legend Diff" },
      },
    ],
  },
  {
    id: "file",
    title: "File",
    placement: { before: "Window" },
    items: [
      {
        id: "startWindow",
        title: "New Window",
        targetTitle: "New",
        enabled: true,
        shortcut: { key: "n", modifiers: commandModifier },
      },
      {
        id: "openFolder",
        title: "Open Folder...",
        targetTitles: [...openTargetTitles, "Open Folder", "Open Folder...", "Open Folder…"],
        enabled: true,
        shortcut: { key: "o", modifiers: commandModifier },
      },
      {
        id: "compareFiles",
        title: "Compare Files...",
        enabled: true,
        placement: { before: "Open Recent" },
        shortcut: { key: "o", modifiers: commandModifier | optionModifier },
      },
      {
        id: "openUrl",
        title: "Open URL...",
        enabled: true,
        placement: { before: "Open Recent" },
        shortcut: { key: "l", modifiers: commandModifier },
      },
      {
        id: "openFromClipboard",
        title: "Open from Clipboard",
        enabled: true,
        placement: { before: "Open Recent" },
        shortcut: { key: "o", modifiers: commandModifier | shiftModifier },
      },
      {
        id: "hidePageSetup",
        targetTitles: ["Page Setup...", "Page Setup…"],
        hidden: true,
      },
      {
        id: "hidePrint",
        targetTitles: ["Print...", "Print…"],
        hidden: true,
      },
      { separator: true, id: "separator-file-diff", placement: { before: "Close" } },
      {
        id: "reload",
        title: "Reload",
        enabled: false,
        placement: { before: "Close" },
        shortcut: { key: "r", modifiers: commandModifier },
      },
      {
        id: "revealInFinder",
        title: "Reveal in Finder",
        enabled: false,
        placement: { before: "Close" },
      },
      { separator: true, id: "separator-file-copy", placement: { before: "Close" } },
      {
        id: "copySource",
        title: "Copy Source",
        enabled: false,
        placement: { before: "Close" },
        shortcut: { key: "c", modifiers: commandModifier | optionModifier },
      },
      {
        id: "copyFilePath",
        title: "Copy File Path",
        enabled: false,
        placement: { before: "Close" },
      },
      {
        id: "copyRelativePath",
        title: "Copy Relative Path",
        enabled: false,
        placement: { before: "Close" },
        shortcut: { key: "c", modifiers: commandModifier | optionModifier | shiftModifier },
      },
      { separator: true, id: "separator-file-close", placement: { before: "Close" } },
      {
        id: "save",
        targetTitles: saveTargetTitles,
        enabled: false,
        hidden: true,
        placement: { before: "Close" },
      },
      {
        id: "hideSaveAs",
        targetTitles: saveAsTargetTitles,
        hidden: true,
      },
    ],
  },
  {
    id: "view",
    title: "View",
    placement: { before: "Window" },
    items: [
      {
        id: "hideCustomizeToolbar",
        targetTitles: ["Customize Toolbar...", "Customize Toolbar…"],
        hidden: true,
      },
      {
        id: "toggleSidebar",
        title: "Show Sidebar",
        targetTitles: ["Show Sidebar", "Hide Sidebar"],
        enabled: false,
        shortcut: { key: "s", modifiers: commandModifier | optionModifier },
      },
      {
        id: "filterFiles",
        title: "Search",
        enabled: false,
        placement: { after: "Show Sidebar" },
        shortcut: { key: "f", modifiers: commandModifier },
      },
      { separator: true, id: "separator-view-mode", placement: { before: "Enter Full Screen" } },
      {
        id: "viewUnified",
        title: "Unified",
        checked: true,
        enabled: false,
        placement: { before: "Enter Full Screen" },
        shortcut: { key: "1", modifiers: commandModifier },
      },
      {
        id: "viewBlocks",
        title: "Side-by-Side",
        checked: false,
        enabled: false,
        placement: { before: "Enter Full Screen" },
        shortcut: { key: "2", modifiers: commandModifier },
      },
      { separator: true, id: "separator-view-hunks", placement: { before: "Enter Full Screen" } },
      {
        id: "previousHunk",
        title: "Previous Hunk",
        enabled: false,
        placement: { before: "Enter Full Screen" },
        shortcut: { key: "[", modifiers: commandModifier },
      },
      {
        id: "nextHunk",
        title: "Next Hunk",
        enabled: false,
        placement: { before: "Enter Full Screen" },
        shortcut: { key: "]", modifiers: commandModifier },
      },
      {
        id: "showOnlyHunks",
        title: "Show Only Hunks",
        checked: true,
        enabled: false,
        placement: { before: "Enter Full Screen" },
      },
      { separator: true, id: "separator-view-fullscreen", placement: { before: "Enter Full Screen" } },
    ],
  },
];
