require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require 'pathname'

shell_dir = Pathname.new(ENV['LEGEND_SHELL_ROOT'] || File.expand_path("..", __dir__))
app_root = Pathname.new(ENV['LEGEND_APP_ROOT'] || shell_dir.to_s)
rn_macos_absolute_path = shell_dir.join("node_modules", "react-native-macos")
rn_macos_path = rn_macos_absolute_path.relative_path_from(Pathname.new(__dir__)).to_s
require "#{rn_macos_absolute_path}/scripts/react_native_pods.rb"

ENV['RCT_NEW_ARCH_ENABLED'] = "1";

prepare_react_native_project!

target 'legendapp-shell-macos' do
  platform :osx, '14.0'
  use_expo_modules!

  config_command = [
    'npx',
    'expo-modules-autolinking',
    'react-native-config',
    '--json',
    '--platform',
    'ios'
  ]
  config = use_native_modules!(config_command)

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => rn_macos_path,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => app_root.to_s
  )

  post_install do |installer|
    react_native_post_install(installer, rn_macos_path)

    installer.pods_project.targets.each do |target|
      next unless target.name == 'fmt'

      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++17'
      end
    end
  end
end
