// Shared standalone-test build. Pod sources come from the same manifest.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const vendor = join(root, "vendor/tree-sitter");
const output = process.argv[2];
if (!output || output.startsWith("--")) throw new Error("Usage: compile-tree-sitter.ts <build-directory> [--update-symbols]");
mkdirSync(output, { recursive: true });
const archIndex = process.argv.indexOf("--arch");
const arch = archIndex < 0 ? undefined : process.argv[archIndex + 1];
if (arch && !["arm64", "x86_64"].includes(arch)) throw Error("Invalid build architecture");
const grammars: { name: string }[] = JSON.parse(readFileSync(join(root, "../../grammars/catalog.json"), "utf8")).grammars.filter((g: { testFixture?: boolean }) => g.testFixture);
const sources = [{ name: "runtime", file: join(vendor, "runtime/src/lib.c"), include: join(vendor, "runtime/include") }];
for (const { name } of process.argv.includes("--runtime-only") ? [] : grammars) {
  for (const kind of ["parser", "scanner"]) {
    const file = join(vendor, name, "src", `${kind}.c`);
    if (existsSync(file)) sources.push({ name: `${name}-${kind}`, file, include: join(vendor, name, "src") });
  }
}
const prefix = join(vendor, "Symbols.h");
function compile(prefixed: boolean) {
  for (const source of sources) execFileSync("clang", ["-std=c11", "-O2", ...(arch ? ["-arch", arch] : []), `-I${source.include}`,
    ...(prefixed ? ["-include", prefix] : []), "-c", source.file, "-o", resolve(output, `${source.name}.o`)], { stdio: "inherit" });
}
function symbols(): string[] {
  const objects = sources.map((source) => resolve(output, `${source.name}.o`));
  const result = execFileSync("nm", [...(process.platform === "darwin" ? ["-gU"] : ["-g", "--defined-only"]), ...objects], { encoding: "utf8" });
  return [...new Set(result.split("\n").flatMap((line) => {
    const match = line.trim().match(/^[a-fA-F0-9]+\s+[A-Za-z]\s+(\w+)$/);
    return match ? [process.platform === "darwin" ? match[1].replace(/^_/, "") : match[1]] : [];
  }))].sort();
}
if (process.argv.includes("--update-symbols")) {
  compile(false);
  const exported = symbols();
  if (!exported.includes("ts_parser_new")) throw new Error("Could not discover Tree-sitter exports");
  writeFileSync(prefix, "// Generated by scripts/compile-tree-sitter.ts --update-symbols.\n"
    + "// Isolate our runtime AND grammars from other native pods embedding Tree-sitter.\n#pragma once\n"
    + exported.map((name) => `#define ${name} legend_syntax_${name}\n`).join(""));
}
compile(true);
const leaked = symbols().filter((name) => !name.startsWith("legend_syntax_"));
if (leaked.length) throw new Error(`Unisolated native symbols (regenerate Symbols.h): ${leaked.join(", ")}`);
