import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
type Grammar = { name: string; aliases: string[]; extensions: string[]; filenames: string[]; scope: string; symbol: string; inherits: string[]; refinements: string[] };
const allGrammars: (Grammar & { bundled?: boolean })[] = JSON.parse(readFileSync(new URL("../../grammars/catalog.json", root), "utf8")).grammars;
const grammars = allGrammars.filter((g) => g.bundled !== false);
const byName = new Map(grammars.map((grammar) => [grammar.name, grammar]));
const names = new Set<string>();
for (const grammar of grammars) {
  if (!/^tree_sitter_[a-z0-9_]+$/.test(grammar.symbol)) throw new Error(`Invalid grammar symbol: ${grammar.symbol}`);
  for (const name of [grammar.name, ...grammar.aliases]) {
    if (names.has(name) || !/^[a-z0-9_-]+$/.test(name)) throw new Error(`Invalid or duplicate language: ${name}`);
    names.add(name);
  }
}
function upstream(name: string, ancestors: string[] = []): string {
  const grammar = byName.get(name);
  if (!grammar || ancestors.includes(name)) throw new Error(`Invalid query inheritance: ${[...ancestors, name]}`);
  return grammar.inherits.map((parent) => upstream(parent, [...ancestors, name])).join("\n")
    + "\n" + readFileSync(new URL(`vendor/tree-sitter/${name}/highlights.scm`, root), "utf8");
}
const declarations = grammars.map((grammar) => `extern "C" const TSLanguage* ${grammar.symbol}();`).join("\n");
const queryName = (grammar: Grammar) => `query_${grammar.name.replaceAll("-", "_")}`;
const captureCatalog: { name: string; scope: string }[] = [];
const captureOffsets: number[] = [];
const queries = grammars.map((grammar) => {
  const query = upstream(grammar.name) + "\n" + grammar.refinements.map((name) =>
    readFileSync(new URL(`../../grammars/queries/${name}-refinements.scm`, root), "utf8")).join("\n");
  if (query.includes(')SCM"')) throw new Error("Query contains reserved C++ delimiter");
  captureOffsets.push(captureCatalog.length);
  // A stable build-time catalog means a newly visited fence never changes IDs
  // or forces parser/query construction for every other language at startup.
  const captures = new Set([...query.matchAll(/@([\w.-]+)/g)].map((match) => match[1]));
  for (const name of captures) captureCatalog.push({ name, scope: grammar.scope });
  return `inline constexpr auto ${queryName(grammar)} = R"SCM(${query})SCM";`;
}).join("\n");
const entries = grammars.map((grammar, index) => `  {${JSON.stringify(grammar.name)}, ${JSON.stringify(grammar.scope)}, &${grammar.symbol}, ${queryName(grammar)}, ${captureOffsets[index]}, ${(captureOffsets[index + 1] ?? captureCatalog.length) - captureOffsets[index]}},`).join("\n");
const aliases = grammars.flatMap((grammar, index) => [grammar.name, ...grammar.aliases].map((alias) =>
  `  {${JSON.stringify(alias)}, ${index}},`)).join("\n");
const header = `// Generated by scripts/embed-tree-sitter-queries.ts from pinned sources and the grammar manifest.
#pragma once
${declarations}
namespace margelo::nitro::legendapps::syntaxparser {
struct TreeSitterPathLanguage { const char* value; const char* language; };
inline constexpr TreeSitterPathLanguage treeSitterFilenames[] = {
${allGrammars.flatMap((g) => g.filenames.map((value) => `  {${JSON.stringify(value)}, ${JSON.stringify(g.name)}},`)).join("\n")}
};
inline constexpr TreeSitterPathLanguage treeSitterExtensions[] = {
${allGrammars.flatMap((g) => g.extensions.map((value) => `  {${JSON.stringify(value)}, ${JSON.stringify(g.name)}},`)).join("\n")}
};
struct TreeSitterCanonicalAlias { const char* name; const char* canonical; };
inline constexpr TreeSitterCanonicalAlias treeSitterCanonicalAliases[] = {
${allGrammars.flatMap((g) => [g.name, ...g.aliases].map((name) => `  {${JSON.stringify(name)}, ${JSON.stringify(g.name)}},`)).join("\n")}
};
${queries}
struct TreeSitterLanguage {
  const char* name;
  const char* scope;
  const TSLanguage* (*grammar)();
  const char* query;
  unsigned captureOffset, captureCount;
};
struct TreeSitterCapture { const char* name; const char* scope; };
inline constexpr TreeSitterCapture treeSitterCaptures[] = {
${captureCatalog.map(({ name, scope }) => `  {${JSON.stringify(name)}, ${JSON.stringify(scope)}},`).join("\n")}
};
inline const TreeSitterLanguage treeSitterLanguages[] = {
${entries}
};
struct TreeSitterAlias { const char* name; unsigned index; };
inline constexpr TreeSitterAlias treeSitterAliases[] = {
${aliases}
};
}
`;
const output = new URL("vendor/tree-sitter/queries/Highlights.hpp", root);
if (process.argv.includes("--check")) {
  if (readFileSync(output, "utf8") !== header) throw new Error("Embedded Tree-sitter registry/queries are stale");
} else writeFileSync(fileURLToPath(output), header);
