import type { AppManifest } from "../../scripts/lib/types";

const manifest = {
  id: "music",
  displayName: "Legend Music",
  platforms: ["macos", "ios", "android"],
  bundleIds: {
    ios: "app.legend.music",
    macos: "app.legend.music.macos",
  },
  androidPackage: "app.legend.music",
  nativeModules: {
    macos: [
      "@legend-desktop/appkit-split-view",
      "@legend-desktop/app-exit",
      "@legend-desktop/app-storage",
      "@legend-desktop/auto-updater",
      "@legend-desktop/audio-player",
      "@legend-desktop/context-menu",
      "@legend-desktop/file-dialog",
      "@legend-desktop/file-system-watcher",
      "@legend-desktop/global-hotkey",
      "@legend-desktop/media-library-scanner",
      "@legend-desktop/media-tags",
      "@legend-desktop/native-menu",
      "@legend-desktop/window-manager",
    ],
    ios: [
      "@legend-desktop/appkit-split-view",
      "@legend-desktop/app-exit",
      "@legend-desktop/app-storage",
      "@legend-desktop/auto-updater",
      "@legend-desktop/audio-player",
      "@legend-desktop/context-menu",
      "@legend-desktop/file-dialog",
      "@legend-desktop/file-system-watcher",
      "@legend-desktop/global-hotkey",
      "@legend-desktop/media-library-scanner",
      "@legend-desktop/media-tags",
      "@legend-desktop/native-menu",
      "@legend-desktop/window-manager",
    ],
    android: [
      "@legend-desktop/appkit-split-view",
      "@legend-desktop/app-exit",
      "@legend-desktop/app-storage",
      "@legend-desktop/auto-updater",
      "@legend-desktop/audio-player",
      "@legend-desktop/context-menu",
      "@legend-desktop/file-dialog",
      "@legend-desktop/file-system-watcher",
      "@legend-desktop/global-hotkey",
      "@legend-desktop/media-library-scanner",
      "@legend-desktop/media-tags",
      "@legend-desktop/native-menu",
      "@legend-desktop/window-manager",
    ],
  },
} satisfies AppManifest;

export default manifest;
