import type { AppManifest } from "../../scripts/lib/types";

const manifest = {
  id: "test-kitchen-sink",
  displayName: "Legend Test Kitchen Sink",
  platforms: ["macos", "ios", "android"],
  bundleIds: {
    ios: "app.legend.testkitchensink",
    macos: "app.legend.testkitchensink.macos",
  },
  androidPackage: "app.legend.testkitchensink",
  nativeModules: {
    macos: [
      "@legend-desktop/app-exit",
      "@legend-desktop/auto-updater",
      "@legend-desktop/appkit-split-view",
      "@legend-desktop/audio-player",
      "@legend-desktop/native-menu",
      "@legend-desktop/file-dialog",
      "@legend-desktop/file-scanner",
      "@legend-desktop/document-scanner",
      "@legend-desktop/context-menu",
      "@legend-desktop/window-controls",
      "@legend-desktop/window-manager",
      "@legend-desktop/global-hotkey",
      "@legend-desktop/file-system-watcher",
      "@legend-desktop/glass-effect-view",
      "@legend-desktop/markdown-block-editor",
      "@legend-desktop/markdown-parser",
      "@legend-desktop/media-tags",
      "@legend-desktop/media-library-scanner",
      "@legend-desktop/sidebar",
      "@legend-desktop/sf-symbol",
      "react-native-enriched-markdown",
    ],
    ios: [
      "@legend-desktop/app-exit",
      "@legend-desktop/auto-updater",
      "@legend-desktop/appkit-split-view",
      "@legend-desktop/audio-player",
      "@legend-desktop/native-menu",
      "@legend-desktop/file-dialog",
      "@legend-desktop/file-scanner",
      "@legend-desktop/document-scanner",
      "@legend-desktop/context-menu",
      "@legend-desktop/window-controls",
      "@legend-desktop/window-manager",
      "@legend-desktop/global-hotkey",
      "@legend-desktop/file-system-watcher",
      "@legend-desktop/glass-effect-view",
      "@legend-desktop/markdown-parser",
      "@legend-desktop/media-tags",
      "@legend-desktop/media-library-scanner",
      "@legend-desktop/sidebar",
      "@legend-desktop/sf-symbol",
      "react-native-enriched-markdown",
    ],
    android: [
      "@legend-desktop/app-exit",
      "@legend-desktop/auto-updater",
      "@legend-desktop/appkit-split-view",
      "@legend-desktop/audio-player",
      "@legend-desktop/native-menu",
      "@legend-desktop/file-dialog",
      "@legend-desktop/file-scanner",
      "@legend-desktop/document-scanner",
      "@legend-desktop/context-menu",
      "@legend-desktop/window-controls",
      "@legend-desktop/window-manager",
      "@legend-desktop/global-hotkey",
      "@legend-desktop/file-system-watcher",
      "@legend-desktop/glass-effect-view",
      "@legend-desktop/media-tags",
      "@legend-desktop/media-library-scanner",
      "@legend-desktop/sidebar",
      "@legend-desktop/sf-symbol",
      "react-native-enriched-markdown",
    ],
  },
} satisfies AppManifest;

export default manifest;
