import type { AppManifest } from "../../scripts/lib/types";

const manifest = {
  id: "test-kitchen-sink",
  displayName: "Legend Test Kitchen Sink",
  platforms: ["macos", "ios", "android"],
  bundleIds: {
    ios: "so.legend.testkitchensink",
    macos: "so.legend.testkitchensink.macos",
  },
  androidPackage: "so.legend.testkitchensink",
  hostWindow: {
    macos: {
      startupBackgroundColors: {
        dark: "#f8fafc",
        light: "#f8fafc",
      },
    },
  },
  nativeModules: {
    macos: [
      "@legend-apps/app-exit",
      "@legend-apps/auto-updater",
      "@legend-apps/command-runner",
      "@legend-apps/audio-player",
      "@legend-apps/appkit-split-view",
      "@legend-apps/native-menu",
      "@legend-apps/drag-drop",
      "@legend-apps/file-dialog",
      "@legend-apps/file-scanner",
      "@legend-apps/document-scanner",
      "@legend-apps/context-menu",
      "@legend-apps/window-controls",
      "@legend-apps/window-manager",
      "@legend-apps/global-hotkey",
      "@legend-apps/keyboard-manager",
      "@legend-apps/file-system-watcher",
      "@legend-apps/glass-effect-view",
      "@legend-apps/markdown-block-editor",
      "@legend-apps/markdown-parser",
      "@legend-apps/media-tags",
      "@legend-apps/media-library-scanner",
      "@legend-apps/sidebar",
      "@legend-apps/sf-symbol",
      "@legend-apps/text-input-search",
      "react-native-enriched-markdown",
    ],
    ios: [
      "@legend-apps/app-exit",
      "@legend-apps/auto-updater",
      "@legend-apps/audio-player",
      "@legend-apps/appkit-split-view",
      "@legend-apps/native-menu",
      "@legend-apps/drag-drop",
      "@legend-apps/file-dialog",
      "@legend-apps/file-scanner",
      "@legend-apps/document-scanner",
      "@legend-apps/context-menu",
      "@legend-apps/window-controls",
      "@legend-apps/window-manager",
      "@legend-apps/global-hotkey",
      "@legend-apps/keyboard-manager",
      "@legend-apps/file-system-watcher",
      "@legend-apps/glass-effect-view",
      "@legend-apps/markdown-parser",
      "@legend-apps/media-tags",
      "@legend-apps/media-library-scanner",
      "@legend-apps/sidebar",
      "@legend-apps/sf-symbol",
      "@legend-apps/text-input-search",
      "react-native-enriched-markdown",
    ],
    android: [
      "@legend-apps/app-exit",
      "@legend-apps/auto-updater",
      "@legend-apps/appkit-split-view",
      "@legend-apps/native-menu",
      "@legend-apps/file-dialog",
      "@legend-apps/file-scanner",
      "@legend-apps/document-scanner",
      "@legend-apps/context-menu",
      "@legend-apps/window-controls",
      "@legend-apps/window-manager",
      "@legend-apps/global-hotkey",
      "@legend-apps/file-system-watcher",
      "@legend-apps/glass-effect-view",
      "@legend-apps/media-tags",
      "@legend-apps/media-library-scanner",
      "@legend-apps/sidebar",
      "@legend-apps/sf-symbol",
      "react-native-enriched-markdown",
    ],
  },
  release: {
    macos: {
      build: "1",
      sparkle: {
        publicEdKey: "znYpZf1eiRuYn6a/gq4mBX6uWQWEc49rTZTlAAraJRU=",
      },
    },
  },
} satisfies AppManifest;

export default manifest;
